version: '3'
services:
  ############################
  # Node app + Dapr sidecar
  ############################
  nodeapp:
      image: "dapr-pilot/node-people-server"
      ports:
        - "3000:3000"
        - "50002:50002" # Dapr instances communicate over gRPC so we need to expose the gRPC port
      environment:
        - "APR_PROTOCOL=http"
        - "DAPR_HOST=localhost"
        - "DAPR_HTTP_PORT=3501"
      networks:
        - dapr-network
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "nodeapp",
     "-app-port", "3000",
     "-dapr-http-port", "3501",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp" # Attach the nodeapp-dapr service to the nodeapp network namespace
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr:1.10.6"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks: 
      - dapr-network
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
    networks:
      - dapr-network
networks:
    dapr-network: