apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "mongo-nodeport-svc.mongodb.svc.cluster.local:27017"
  - name: username
    value: "adminuser"
  - name: password
    value: "password123"
  - name: databaseName
    value: "daprStore"
  - name: collectionName
    value: "daprStore"
  - name: params
    value: "?authSource=admin"

    